from unittest import TestCase

from services import tubes_train_service


class TubeTrainServiceTestCases(TestCase):
    def test_count_tube_problems(self):
        # given
        expected_result = {
            'BakerlooMD': 1,
            'BakerlooSD': 1,
            'BakerlooPS': 1,
            'BakerlooFS': 1,
            'BakerlooTotalTime': '20 seconds.',
            'CentralMD': 1,
            'CentralSD': 1,
            'CentralPS': 1,
            'CentralFS': 1,
            'CentralTotalTime': '20 seconds.',
            'CircleMD': 1,
            'CircleSD': 1,
            'CirclePS': 1,
            'CircleFS': 1,
            'CircleTotalTime': '20 seconds.',
            'DistrictMD': 1,
            'DistrictSD': 1,
            'DistrictPS': 1,
            'DistrictFS': 1,
            'DistrictTotalTime': '20 seconds.',
            'HammersmithMD': 1,
            'HammersmithSD': 1,
            'HammersmithPS': 1,
            'HammersmithFS': 1,
            'HammersmithTotalTime': '20 seconds.',
            'JubileeMD': 1,
            'JubileeSD': 1,
            'JubileePS': 1,
            'JubileeFS': 1,
            'JubileeTotalTime': '20 seconds.',
            'MetropolitanMD': 1,
            'MetropolitanSD': 1,
            'MetropolitanPS': 1,
            'MetropolitanFS': 1,
            'MetropolitanTotalTime': '20 seconds.',
            'NorthernMD': 1,
            'NorthernSD': 1,
            'NorthernPS': 1,
            'NorthernFS': 1,
            'NorthernTotalTime': '20 seconds.',
            'PiccadillyMD': 1,
            'PiccadillySD': 1,
            'PiccadillyPS': 1,
            'PiccadillyFS': 1,
            'PiccadillyTotalTime': '20 seconds.',
            'VictoriaMD': 1,
            'VictoriaSD': 1,
            'VictoriaPS': 1,
            'VictoriaFS': 1,
            'VictoriaTotalTime': '20 seconds.',
            'WaterlooMD': 1,
            'WaterlooSD': 1,
            'WaterlooPS': 1,
            'WaterlooFS': 1,
            'WaterlooTotalTime': '20 seconds.'
        }
        problem_list = [
            'bakerloo has Minor Delays',
            'bakerloo has Severe Delays',
            'bakerloo has Part Suspended',
            'bakerloo has Suspended',
            'central has Minor Delays',
            'central has Severe Delays',
            'central has Part Suspended',
            'central has Suspended',
            'circle has Minor Delays',
            'circle has Severe Delays',
            'circle has Part Suspended',
            'circle has Suspended',
            'district has Minor Delays',
            'district has Severe Delays',
            'district has Part Suspended',
            'district has Suspended',
            'hammersmith-city has Minor Delays',
            'hammersmith-city has Severe Delays',
            'hammersmith-city has Part Suspended',
            'hammersmith-city has Suspended',
            'jubilee has Minor Delays',
            'jubilee has Severe Delays',
            'jubilee has Part Suspended',
            'jubilee has Suspended',
            'metropolitan has Minor Delays',
            'metropolitan has Severe Delays',
            'metropolitan has Part Suspended',
            'metropolitan has Suspended',
            'northern has Minor Delays',
            'northern has Severe Delays',
            'northern has Part Suspended',
            'northern has Suspended',
            'piccadilly has Minor Delays',
            'piccadilly has Severe Delays',
            'piccadilly has Part Suspended',
            'piccadilly has Suspended',
            'victoria has Minor Delays',
            'victoria has Severe Delays',
            'victoria has Part Suspended',
            'victoria has Suspended',
            'waterloo-city has Minor Delays',
            'waterloo-city has Severe Delays',
            'waterloo-city has Part Suspended',
            'waterloo-city has Suspended'
        ]

        # when
        result = tubes_train_service.count_tube_problems(problem_list)

        # then
        self.assertTrue(expected_result, result)
