PARADISE = 'paradise'
FLAME = 'flame'
YELLOW_GREEN = 'yellow_green'
MAGENTA = 'magenta'
CYAN = 'cyan'
YELLOW = 'yellow'
BROWN = 'brown'
BLACK = 'black'
WHITE = 'white'
PURPLE = 'purple'
BLUE = 'blue'
GREEN = 'green'
ORANGE = 'orange'
RED = 'red'

RED_RGB_COLOUR = [255, 0, 0]
ORANGE_RGB_COLOUR = [224, 64, 0]
GREEN_RGB_COLOUR = [0, 255, 0]
YELLOW_GREEN_RGB_COLOUR = [153, 204, 0]
BLUE_RGB_COLOUR = [0, 0, 255]
PURPLE_RGB_COLOUR = [75, 0, 130]
WHITE_RGB_COLOUR = [255, 255, 255]
BLACK_RGB_COLOUR = [1, 1, 1]
BROWN_RGB_COLOUR = [160, 96, 32]
YELLOW_RGB_COLOUR = [255, 255, 0]
CYAN_RGB_COLOUR = [0, 255, 255]
MAGENTA_RGB_COLOUR = [192, 0, 192]
FLAME_RGB_COLOUR = [242, 85, 44]
PARADISE_RGB_COLOUR = [144, 222, 227]
colors = {
    RED: RED_RGB_COLOUR,
    ORANGE: ORANGE_RGB_COLOUR,
    GREEN: GREEN_RGB_COLOUR,
    BLUE: BLUE_RGB_COLOUR,
    PURPLE: PURPLE_RGB_COLOUR,
    WHITE: WHITE_RGB_COLOUR,
    BLACK: BLACK_RGB_COLOUR,
    BROWN: BROWN_RGB_COLOUR,
    YELLOW: YELLOW_RGB_COLOUR,
    CYAN: CYAN_RGB_COLOUR,
    MAGENTA: MAGENTA_RGB_COLOUR,
    YELLOW_GREEN: YELLOW_GREEN_RGB_COLOUR,
    FLAME: FLAME_RGB_COLOUR,
    PARADISE: PARADISE_RGB_COLOUR
}

colors_names = [RED, ORANGE, GREEN, BLUE, PURPLE, WHITE, BLACK, BROWN, YELLOW, CYAN, MAGENTA,
                YELLOW_GREEN, FLAME, PARADISE]
lighting_colors = [RED_RGB_COLOUR, ORANGE_RGB_COLOUR, GREEN_RGB_COLOUR, BLUE_RGB_COLOUR, PURPLE_RGB_COLOUR,
                   WHITE_RGB_COLOUR, BLACK_RGB_COLOUR, BROWN_RGB_COLOUR, YELLOW_RGB_COLOUR, CYAN_RGB_COLOUR,
                   MAGENTA_RGB_COLOUR, YELLOW_GREEN_RGB_COLOUR,
                   FLAME_RGB_COLOUR, PARADISE_RGB_COLOUR]
